apiVersion: platform.darede.io/v1alpha1
kind: Aurora
metadata:
  name: mandradeidp-db
  namespace: mandradeidp
  labels:
    db.engine: postgresql
spec:
  compositionSelector:
    matchLabels:
      db.engine: postgresql
  appName: mandradeidp
  dbSize: M  # M | L (S removed - Aurora minimum is t4g.medium)
  dbEngine: aurora-postgresql  # aurora-postgresql | aurora-mysql | postgresql | mysql
  engineVersion: "16.11"  # PostgreSQL 16.11 (recommended)
  
  # VPC Configuration (auto-populated from platform-params ConfigMap)
  vpcId: "vpc-0a66641a80c762baa"
  
  # Private subnet IDs for Aurora subnet group (must be in different AZs)
  # Auto-populated from EKS cluster VPC configuration
  subnetIds:
    - "subnet-0e482760d4e4f0250"
    - "subnet-001f264a2c946e35c"
    - "subnet-05916f1c5cb54a6a8"
  
  # Security group that will be allowed to connect to Aurora on port 5432
  # Using EKS node security group for direct pod-to-DB connectivity
  allowedSecurityGroupId: "sg-0af4edc484e912aa3"
  
  # Master password secret reference (must exist before creating Aurora)
  masterPasswordSecretRef:
    name: mandradeidp-aurora-master-password
    namespace: mandradeidp
    key: password
