apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mandradeidp
  namespace: argocd
spec:
  project: apps
  source:
    repoURL: https://github.com/darede-labs/idp-mandradeidp.git
    targetRevision: main
    path: infra/argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
